import { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, ChevronDown, Clock3, Dumbbell, MapPin, Plus, Search, ShieldCheck, Users, X } from "lucide-react";

const facilities = [
  { id: "clubhouse", name: "Clubhouse", icon: "🏛️", type: "Community", hours: "6:00 AM – 10:00 PM", capacity: "80 people", fee: "₹1,500 / slot", status: "Available", description: "A spacious venue for celebrations, meetings and community events.", slots: ["10:00 AM", "2:00 PM", "6:00 PM"] },
  { id: "gym", name: "Fitness Centre", icon: "🏋️", type: "Wellness", hours: "5:30 AM – 10:00 PM", capacity: "25 people", fee: "Free for residents", status: "Available", description: "Modern fitness equipment with dedicated workout and yoga zones.", slots: ["6:00 AM", "7:00 AM", "6:00 PM"] },
  { id: "pool", name: "Swimming Pool", icon: "🏊", type: "Wellness", hours: "7:00 AM – 8:00 PM", capacity: "20 people", fee: "₹200 / session", status: "Available", description: "Temperature-controlled pool with changing rooms and lifeguard support.", slots: ["8:00 AM", "4:00 PM", "6:00 PM"] },
  { id: "court", name: "Badminton Court", icon: "🏸", type: "Sports", hours: "6:00 AM – 9:00 PM", capacity: "4 people", fee: "₹150 / hour", status: "Limited", description: "Indoor court with professional flooring and equipment rental.", slots: ["7:00 AM", "5:00 PM", "8:00 PM"] },
  { id: "garden", name: "Rooftop Garden", icon: "🌿", type: "Community", hours: "6:00 AM – 9:00 PM", capacity: "40 people", fee: "Free for residents", status: "Available", description: "A peaceful landscaped garden with city views and seating areas.", slots: ["9:00 AM", "3:00 PM", "7:00 PM"] },
  { id: "hall", name: "Multipurpose Hall", icon: "🎉", type: "Community", hours: "8:00 AM – 11:00 PM", capacity: "120 people", fee: "₹2,000 / slot", status: "Maintenance", description: "A flexible indoor space for larger functions, classes and events.", slots: [] },
];

function Facilities() {
  const [selected, setSelected] = useState(facilities[0]); const [filter, setFilter] = useState("All Facilities"); const [search, setSearch] = useState(""); const [showBooking, setShowBooking] = useState(false); const [notice, setNotice] = useState("");
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const shown = useMemo(() => facilities.filter(f => `${f.name} ${f.type}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All Facilities" || f.type === filter)), [filter, search]);
  const book = (event) => { event.preventDefault(); const time = new FormData(event.currentTarget).get("slot"); setShowBooking(false); notify(`${selected.name} booked for ${time}.`); };
  return <div className="facilities-page">{notice && <div className="facility-notice" role="status">{notice}</div>}
    <header className="facility-title"><div><h1>Facility Booking</h1><p>Explore amenities and reserve a time that works for you</p></div><button className="facility-primary" onClick={() => setShowBooking(true)}><Plus size={17}/> Book a Facility</button></header>
    <section className="facility-hero"><div><span>YOUR AMENITIES</span><h2>Everything you need, <em>right at home.</em></h2><p>Enjoy thoughtfully maintained community spaces built for fitness, celebrations and everyday relaxation.</p><button className="facility-primary" onClick={() => document.getElementById("facility-grid")?.scrollIntoView({ behavior: "smooth" })}>Explore Facilities</button></div><div className="facility-hero-art"><div className="hero-orbit orbit-one"></div><div className="hero-orbit orbit-two"></div><Dumbbell size={70}/><span>6 premium amenities</span></div></section>
    <div className="facility-filters"><label><Search size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search facilities..."/></label><div><select value={filter} onChange={e => setFilter(e.target.value)}><option>All Facilities</option><option>Community</option><option>Wellness</option><option>Sports</option></select><ChevronDown size={15}/></div><button onClick={() => { setSearch(""); setFilter("All Facilities"); }}>Clear Filters</button></div>
    <div id="facility-grid" className="facility-grid">{shown.map(f => <article className={`facility-card ${selected.id === f.id ? "selected" : ""}`} key={f.id}><div className="facility-card-visual"><span>{f.icon}</span><em className={f.status.toLowerCase()}>{f.status}</em></div><div className="facility-card-body"><p>{f.type}</p><h3>{f.name}</h3><div><Clock3 size={14}/>{f.hours}</div><div><Users size={14}/>{f.capacity}</div><footer><strong>{f.fee}</strong><button onClick={() => { setSelected(f); f.status === "Maintenance" ? notify(`${f.name} is currently under maintenance.`) : setShowBooking(true); }}>Book Now</button></footer></div><button className="facility-card-link" onClick={() => setSelected(f)}>View details →</button></article>)}</div>
    <section className="facility-detail"><div className="facility-detail-intro"><span>{selected.icon}</span><div><p>{selected.type}</p><h2>{selected.name}</h2><em className={selected.status.toLowerCase()}>{selected.status}</em></div></div><div className="facility-detail-copy"><p>{selected.description}</p><div><span><Clock3 size={15}/>{selected.hours}</span><span><Users size={15}/>{selected.capacity}</span><span><MapPin size={15}/> Green Valley Residency</span></div></div><div className="facility-slots"><h3>Available slots today</h3>{selected.slots.length ? <div>{selected.slots.map(slot => <button key={slot} onClick={() => { setShowBooking(true); notify(`${slot} selected for ${selected.name}.`); }}>{slot}</button>)}</div> : <p>Bookings are temporarily unavailable while this facility is under maintenance.</p>}</div><button className="facility-primary" disabled={selected.status === "Maintenance"} onClick={() => setShowBooking(true)}><CalendarDays size={16}/> Reserve {selected.name}</button></section>
    <section className="facility-rules"><ShieldCheck size={25}/><div><h3>Facility guidelines</h3><p>Please arrive on time, keep shared spaces clean, and cancel at least two hours before a booking if your plans change.</p></div><button onClick={() => notify("Facility guidelines opened.")}>View All Rules</button></section>
    {showBooking && <div className="facility-modal-backdrop" onClick={() => setShowBooking(false)}><form className="facility-modal" onClick={e => e.stopPropagation()} onSubmit={book}><div><h2>Reserve {selected.name}</h2><button type="button" onClick={() => setShowBooking(false)}><X size={19}/></button></div><p>{selected.fee} · {selected.hours}</p><label>Booking date<input required type="date"/></label><label>Choose a time slot<select name="slot">{(selected.slots.length ? selected.slots : ["No slots available"]).map(slot => <option key={slot}>{slot}</option>)}</select></label><footer><button type="button" onClick={() => setShowBooking(false)}>Cancel</button><button className="facility-primary" disabled={!selected.slots.length}>Confirm Booking</button></footer></form></div>}
  </div>;
}
export default Facilities;
