import { useMemo, useState } from "react";
import { BellRing, CalendarDays, CheckCircle2, ChevronDown, FileText, Megaphone, Pin, Plus, Search, Users, X } from "lucide-react";

const noticeSeed = [
  { id: "NT-104", title: "Scheduled Water Supply Maintenance", category: "Maintenance", date: "30 May 2026", audience: "All Residents", pinned: true, reads: 214, body: "Water supply will be temporarily unavailable from 10:00 AM to 1:00 PM on Saturday due to scheduled pipeline maintenance. Please store sufficient water in advance." },
  { id: "NT-103", title: "Annual General Meeting 2026", category: "Community", date: "28 May 2026", audience: "All Owners", pinned: true, reads: 178, body: "The Annual General Meeting will be held on 15 June 2026 at 5:00 PM in the Clubhouse. The agenda and supporting documents will be shared shortly." },
  { id: "NT-102", title: "New Visitor Entry Guidelines", category: "Security", date: "25 May 2026", audience: "All Residents", pinned: false, reads: 203, body: "All visitors must be pre-approved through the society portal. Please ensure delivery partners and service providers have the correct flat number before arrival." },
  { id: "NT-101", title: "Swimming Pool Timings Revised", category: "Facilities", date: "22 May 2026", audience: "All Residents", pinned: false, reads: 165, body: "Swimming pool timings are now 7:00 AM to 8:00 PM. Children below 12 years must be accompanied by an adult." },
  { id: "NT-100", title: "June Maintenance Payment Reminder", category: "Payments", date: "20 May 2026", audience: "All Residents", pinned: false, reads: 190, body: "Kindly complete your June maintenance payment by 5 June 2026 to avoid a late payment charge." },
];
const categoryClass = (name) => name.toLowerCase();

function Notices() {
  const [notices, setNotices] = useState(noticeSeed); const [selected, setSelected] = useState(noticeSeed[0]); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All Categories"); const [showForm, setShowForm] = useState(false); const [acknowledged, setAcknowledged] = useState([]); const [notice, setNotice] = useState("");
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const shown = useMemo(() => notices.filter(item => `${item.title} ${item.category} ${item.audience}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All Categories" || item.category === filter)), [notices, search, filter]);
  const publish = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const item = { id: `NT-${105 + notices.length}`, title: data.get("title"), category: data.get("category"), audience: data.get("audience"), body: data.get("body"), date: "Today", reads: 0, pinned: data.get("pinned") === "on" }; setNotices(list => [item, ...list]); setSelected(item); setShowForm(false); notify("Notice published successfully."); };
  const acknowledge = () => { if (!acknowledged.includes(selected.id)) setAcknowledged(ids => [...ids, selected.id]); notify("Notice acknowledged."); };
  return <div className="notices-page">{notice && <div className="notice-toast" role="status">{notice}</div>}
    <header className="notice-title"><div><h1>Notice Board</h1><p>Stay informed about important society updates and announcements</p></div><button className="notice-primary" onClick={() => setShowForm(true)}><Plus size={17}/> Create Notice</button></header>
    <div className="notice-stats"><NStat icon={<FileText/>} value={notices.length} label="Active Notices" color="purple"/><NStat icon={<Pin/>} value={notices.filter(n => n.pinned).length} label="Pinned Notices" color="amber"/><NStat icon={<Users/>} value="236" label="Residents Reached" color="blue"/><NStat icon={<BellRing/>} value="98%" label="Read Rate" color="green"/></div>
    <section className="notice-featured"><div><span><Pin size={14}/> PINNED NOTICE</span><h2>{notices.find(n => n.pinned)?.title}</h2><p>{notices.find(n => n.pinned)?.body}</p><button onClick={() => setSelected(notices.find(n => n.pinned))}>Read Full Notice →</button></div><CalendarDays size={58}/></section>
    <div className="notice-layout"><section className="notice-list-card"><div className="notice-toolbar"><label><Search size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search notices..."/></label><div className="notice-filter"><select value={filter} onChange={e => setFilter(e.target.value)}><option>All Categories</option><option>Maintenance</option><option>Community</option><option>Security</option><option>Facilities</option><option>Payments</option></select><ChevronDown size={15}/></div></div><div className="notice-list">{shown.map(item => <button key={item.id} className={`notice-item ${selected.id === item.id ? "active" : ""}`} onClick={() => setSelected(item)}><span className={`notice-icon ${categoryClass(item.category)}`}><Megaphone size={18}/></span><span className="notice-item-copy"><b>{item.title}</b><small>{item.category} · {item.audience}</small><small>{item.date}</small></span>{item.pinned && <Pin size={15} className="notice-pin"/>}</button>)}{shown.length === 0 && <p className="notice-empty">No notices found.</p>}</div></section>
    <aside className="notice-detail"><div className="notice-detail-head"><span className={`notice-category ${categoryClass(selected.category)}`}>{selected.category}</span><button onClick={() => notify("Notice details refreshed.")}><X size={18}/></button></div><h2>{selected.title}</h2><div className="notice-meta"><span><CalendarDays size={14}/>{selected.date}</span><span><Users size={14}/>{selected.audience}</span></div><p>{selected.body}</p><div className="notice-readers"><CheckCircle2 size={18}/><span><b>{selected.reads} residents</b><small>have read this notice</small></span></div><button className="notice-primary full-width" onClick={acknowledge} disabled={acknowledged.includes(selected.id)}>{acknowledged.includes(selected.id) ? <><CheckCircle2 size={16}/> Acknowledged</> : <><CheckCircle2 size={16}/> Acknowledge Notice</>}</button><button className="notice-secondary full-width" onClick={() => notify("Notice shared with your family members.")}>Share with Family</button></aside></div>
    {showForm && <div className="notice-modal-backdrop" onClick={() => setShowForm(false)}><form className="notice-modal" onClick={e => e.stopPropagation()} onSubmit={publish}><div><h2>Create Notice</h2><button type="button" onClick={() => setShowForm(false)}><X size={19}/></button></div><label>Notice title<input required name="title" placeholder="e.g. Community clean-up drive"/></label><div className="notice-form-grid"><label>Category<select name="category"><option>Community</option><option>Maintenance</option><option>Security</option><option>Facilities</option><option>Payments</option></select></label><label>Audience<select name="audience"><option>All Residents</option><option>All Owners</option><option>Tenants</option></select></label></div><label>Message<textarea required name="body" placeholder="Write the announcement..."/></label><label className="pin-check"><input type="checkbox" name="pinned"/> Pin this notice</label><footer><button type="button" onClick={() => setShowForm(false)}>Cancel</button><button className="notice-primary">Publish Notice</button></footer></form></div>}
  </div>;
}
function NStat({ icon, value, label, color }) { return <div className="notice-stat"><span className={color}>{icon}</span><div><strong>{value}</strong><p>{label}</p></div></div>; }
export default Notices;
