import { useMemo, useState } from "react";
import { BadgeIndianRupee, CalendarDays, CheckCircle2, ChevronDown, Download, Eye, Plus, Search, WalletCards, X } from "lucide-react";

const seedPayments = [
  { id: "PAY-1024", resident: "Arjun Mehta", flat: "A-1203", month: "June 2026", amount: 4350, date: "05 Jun 2026", method: "UPI", status: "Paid" },
  { id: "PAY-1023", resident: "Priya Patel", flat: "C-502", month: "June 2026", amount: 4350, date: "04 Jun 2026", method: "Card", status: "Paid" },
  { id: "PAY-1022", resident: "Rahul Sharma", flat: "B-304", month: "June 2026", amount: 4350, date: "-", method: "-", status: "Pending" },
  { id: "PAY-1021", resident: "Amit Singh", flat: "D-204", month: "June 2026", amount: 4350, date: "-", method: "-", status: "Overdue" },
  { id: "PAY-1020", resident: "Sneha Pillai", flat: "A-1102", month: "May 2026", amount: 4350, date: "03 May 2026", method: "Net Banking", status: "Paid" },
];

const money = (amount) => `₹${amount.toLocaleString("en-IN")}`;

function Payments() {
  const [payments, setPayments] = useState(seedPayments); const [selected, setSelected] = useState(seedPayments[0]); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All Status"); const [showPay, setShowPay] = useState(false); const [notice, setNotice] = useState("");
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const visible = useMemo(() => payments.filter(p => `${p.id} ${p.resident} ${p.flat} ${p.month}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All Status" || p.status === filter)), [payments, search, filter]);
  const downloadReceipt = (payment) => { const url = URL.createObjectURL(new Blob([`Payment receipt\nReceipt: ${payment.id}\nResident: ${payment.resident}\nAmount: ${money(payment.amount)}\nStatus: ${payment.status}`], { type: "text/plain" })); const link = document.createElement("a"); link.href = url; link.download = `${payment.id}-receipt.txt`; link.click(); URL.revokeObjectURL(url); notify(`Receipt ${payment.id} downloaded.`); };
  const payNow = (event) => { event.preventDefault(); const current = payments.find(p => p.id === selected.id); const paid = { ...current, status: "Paid", date: "Today", method: "UPI" }; setPayments(list => list.map(p => p.id === paid.id ? paid : p)); setSelected(paid); setShowPay(false); notify(`Payment of ${money(paid.amount)} completed.`); };
  return <div className="payments-page">{notice && <div className="payment-notice" role="status">{notice}</div>}
    <header className="payment-title"><div><h1>Payments & Maintenance</h1><p>View maintenance dues, payment history and receipts</p></div><button className="payment-primary" onClick={() => setShowPay(true)}><Plus size={17}/> Make a Payment</button></header>
    <div className="payment-summary"><Summary icon={<WalletCards/>} label="This Month Collection" value="₹10,44,000" note="92% collection rate" color="purple"/><Summary icon={<CheckCircle2/>} label="Payments Received" value="240" note="₹10,08,000 collected" color="green"/><Summary icon={<CalendarDays/>} label="Pending Payments" value="8" note="₹34,800 outstanding" color="amber"/><Summary icon={<BadgeIndianRupee/>} label="Overdue Payments" value="3" note="Requires follow up" color="red"/></div>
    <div className="payment-layout"><section className="payment-history"><div className="payment-toolbar"><label><Search size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by resident, flat or receipt ID..."/></label><div className="payment-select"><select value={filter} onChange={e => setFilter(e.target.value)}><option>All Status</option><option>Paid</option><option>Pending</option><option>Overdue</option></select><ChevronDown size={15}/></div><button onClick={() => notify("Payment report is ready to export.")}><Download size={15}/> Export</button></div><div className="payment-table-wrap"><table className="payment-table"><thead><tr><th>Receipt ID</th><th>Resident</th><th>Month</th><th>Amount</th><th>Payment Date</th><th>Method</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map(p => <tr key={p.id} className={selected.id === p.id ? "active" : ""} onClick={() => setSelected(p)}><td>{p.id}</td><td><b>{p.resident}</b><small>{p.flat}</small></td><td>{p.month}</td><td>{money(p.amount)}</td><td>{p.date}</td><td>{p.method}</td><td><em className={`payment-status ${p.status.toLowerCase()}`}>{p.status}</em></td><td><div><button title="View payment" onClick={e => { e.stopPropagation(); setSelected(p); notify(`Viewing ${p.id}.`); }}><Eye size={15}/></button>{p.status === "Paid" ? <button title="Download receipt" onClick={e => { e.stopPropagation(); downloadReceipt(p); }}><Download size={15}/></button> : <button title="Pay now" onClick={e => { e.stopPropagation(); setSelected(p); setShowPay(true); }}><BadgeIndianRupee size={15}/></button>}</div></td></tr>)}</tbody></table></div><footer className="payment-footer">Showing {visible.length} payments <button onClick={() => notify("Next payment page selected.")}>Next page →</button></footer></section>
    <aside className="payment-detail"><div className="payment-detail-head"><div><span>Payment Details</span><h2>{selected.id}</h2></div><button onClick={() => notify("Payment details refreshed.")}><X size={18}/></button></div><div className="payment-amount"><span>Maintenance for {selected.month}</span><strong>{money(selected.amount)}</strong><em className={`payment-status ${selected.status.toLowerCase()}`}>{selected.status}</em></div><dl><div><dt>Resident</dt><dd>{selected.resident}</dd></div><div><dt>Flat Number</dt><dd>{selected.flat}</dd></div><div><dt>Payment Date</dt><dd>{selected.date}</dd></div><div><dt>Payment Method</dt><dd>{selected.method}</dd></div></dl>{selected.status === "Paid" ? <button className="payment-primary wide" onClick={() => downloadReceipt(selected)}><Download size={16}/> Download Receipt</button> : <button className="payment-primary wide" onClick={() => setShowPay(true)}><BadgeIndianRupee size={16}/> Pay Now</button>}<button className="payment-secondary wide" onClick={() => notify(`Reminder sent to ${selected.resident}.`)}>Send Payment Reminder</button></aside></div>
    {showPay && <div className="payment-modal-backdrop" onClick={() => setShowPay(false)}><form className="payment-modal" onClick={e => e.stopPropagation()} onSubmit={payNow}><div><h2>Complete Payment</h2><button type="button" onClick={() => setShowPay(false)}><X size={19}/></button></div><p>Pay maintenance for <b>{selected.flat}</b> — {selected.month}</p><strong>{money(selected.amount)}</strong><label>Payment method<select><option>UPI</option><option>Card</option><option>Net Banking</option></select></label><footer><button type="button" onClick={() => setShowPay(false)}>Cancel</button><button className="payment-primary">Pay {money(selected.amount)}</button></footer></form></div>}
  </div>;
}
function Summary({ icon, label, value, note, color }) { return <div className="payment-summary-card"><span className={color}>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></div>; }
export default Payments;
