import { useState } from "react";
import { ArrowRight, CalendarDays, Car, CheckCircle2, CircleDollarSign, ClipboardList, Droplets, Lightbulb, MessageSquareWarning, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import "./ResidentHome.css";

export default function ResidentHome({ user }) {
  const [notice, setNotice] = useState("");
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2400); };
  return <div className="resident-home">{notice && <div className="resident-home-toast">{notice}</div>}
    <section className="resident-home-hero"><div><span>MY HOME · {user?.flat || "Flat A-1203"}</span><h1>Good evening, {user?.name?.split(" ")[0] || "Arjun"}! <span>👋</span></h1><p>Here’s what’s happening around your home today.</p><div className="home-status"><b><i/> All systems active</b><span>Green Valley Residency</span></div></div><div className="home-weather"><Lightbulb size={27}/><strong>28°C</strong><small>Partly cloudy</small></div></section>
    <section className="resident-action-grid"><Link to="/payments" className="resident-action due"><CircleDollarSign/><div><small>MAINTENANCE DUE</small><b>₹ 4,350</b><span>Due on 5 June</span></div><ArrowRight size={17}/></Link><Link to="/complaints" className="resident-action"><MessageSquareWarning/><div><small>MY COMPLAINTS</small><b>2 active requests</b><span>Track updates from the team</span></div><ArrowRight size={17}/></Link><Link to="/visitors" className="resident-action"><UserRoundCheck/><div><small>VISITORS</small><b>Pre-approve a guest</b><span>Faster entry at the gate</span></div><ArrowRight size={17}/></Link></section>
    <div className="resident-home-layout"><section className="resident-home-card"><header><div><span>UP NEXT</span><h2>Your schedule</h2></div><Link to="/calendar">View calendar <ArrowRight size={14}/></Link></header><div className="schedule-item"><time><b>08</b><small>JUN</small></time><div><b>Yoga at the Lawn</b><p><CalendarDays size={14}/> 6:30 AM · Central Lawn</p></div><button onClick={() => notify("You’re registered for Yoga at the Lawn.")}>Join</button></div><div className="schedule-item"><time><b>14</b><small>JUN</small></time><div><b>Community Potluck</b><p><UsersRound size={14}/> 7:00 PM · Clubhouse</p></div><Link to="/community">Details</Link></div></section><section className="resident-home-card home-services"><header><div><span>QUICK SERVICES</span><h2>Get things done</h2></div></header><div><Link to="/parking"><Car/><span>Reserve visitor parking</span><ArrowRight size={15}/></Link><Link to="/complaints"><ClipboardList/><span>Raise a complaint</span><ArrowRight size={15}/></Link><Link to="/facilities"><CalendarDays/><span>Book a facility</span><ArrowRight size={15}/></Link><Link to="/security"><ShieldCheck/><span>Safety & security</span><ArrowRight size={15}/></Link></div></section></div>
    <div className="resident-home-layout bottom"><section className="resident-home-card home-utility"><header><div><span>HOME UTILITIES</span><h2>Usage this month</h2></div><Link to="/reports">View report <ArrowRight size={14}/></Link></header><div className="utility-row"><Droplets/><div><b>Water usage</b><span><i style={{width:"45%"}}/></span><small>45% of monthly estimate</small></div><strong>8.2 kL</strong></div><div className="utility-row"><Lightbulb/><div><b>Energy usage</b><span><i style={{width:"62%"}}/></span><small>62% of monthly estimate</small></div><strong>186 kWh</strong></div></section><section className="resident-home-card home-update"><ShieldCheck size={27}/><div><span>COMMUNITY UPDATE</span><h2>Water supply maintenance</h2><p>Water supply will be unavailable Saturday, 10 AM–1 PM. Please store sufficient water in advance.</p><Link to="/notices">Read notice <ArrowRight size={14}/></Link></div></section></div>
  </div>;
}
