import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../services/api";
import { BadgeCheck, CalendarDays, Car, CheckCircle2, ChevronDown, Clock3, Eye, LogIn, LogOut, Phone, Plus, Search, UserRoundCheck, X } from "lucide-react";

const visitorData = [
  { id: "VIS-501", name: "Rahul Patil", purpose: "Personal Visit", resident: "Arjun Mehta", flat: "A-1203", phone: "+91 98765 10101", vehicle: "MH 09 AB 2345", time: "28 May 2026, 10:30 AM", status: "Checked In" },
  { id: "VIS-500", name: "Amit Shah", purpose: "Delivery", resident: "Priya Patel", flat: "C-502", phone: "+91 98765 10102", vehicle: "-", time: "27 May 2026, 06:15 PM", status: "Checked Out" },
  { id: "VIS-499", name: "Priya Desai", purpose: "Personal Visit", resident: "Rahul Sharma", flat: "B-304", phone: "+91 98765 10103", vehicle: "MH 09 XY 9821", time: "26 May 2026, 11:20 AM", status: "Approved" },
  { id: "VIS-498", name: "Sunil Kumar", purpose: "Service Provider", resident: "Amit Singh", flat: "D-204", phone: "+91 98765 10104", vehicle: "-", time: "25 May 2026, 04:40 PM", status: "Pending" },
  { id: "VIS-497", name: "Kavita Rao", purpose: "Personal Visit", resident: "Sneha Pillai", flat: "A-1102", phone: "+91 98765 10105", vehicle: "MH 09 CD 5577", time: "24 May 2026, 02:10 PM", status: "Checked Out" },
];
const styleStatus = (value) => value.toLowerCase().replaceAll(" ", "-");

function Visitors() {
  const [visitors, setVisitors] = useState(visitorData); const [selected, setSelected] = useState(visitorData[0]); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All Status"); const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { apiRequest("/visitors").then(items => { if (items.length) { setVisitors(items); setSelected(items[0]); } }).catch(() => notify("Using offline visitor data while the backend is unavailable.")); }, []);
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const visible = useMemo(() => visitors.filter(v => `${v.name} ${v.id} ${v.flat} ${v.resident}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All Status" || v.status === filter)), [visitors, search, filter]);
  const updateStatus = async (status) => { try { const updated = await apiRequest(`/visitors/${selected.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); setVisitors(list => list.map(v => v.id === selected.id ? updated : v)); setSelected(updated); notify(`${selected.name} has been ${status.toLowerCase()}.`); } catch (err) { notify(err.message); } };
  const addVisitor = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const item = await apiRequest("/visitors", { method: "POST", body: JSON.stringify({ name: form.get("name"), purpose: form.get("purpose"), flat: form.get("flat"), phone: form.get("phone") }) }); setVisitors(list => [item, ...list]); setSelected(item); setShowForm(false); notify("Visitor approved and added to the register."); } catch (err) { notify(err.message); } };
  return <div className="visitors-page">{notice && <div className="visitor-notice" role="status">{notice}</div>}
    <header className="visitor-title"><div><h1>Visitor Management</h1><p>Manage visitor approvals, entries and check-outs</p></div><button className="visitor-primary" onClick={() => setShowForm(true)}><Plus size={17}/> Add Visitor</button></header>
    <div className="visitor-stats"><VStat icon={<UserRoundCheck/>} value={visitors.length} label="Today's Visitors" color="purple"/><VStat icon={<LogIn/>} value={visitors.filter(v => v.status === "Checked In").length} label="Currently Inside" color="green"/><VStat icon={<Clock3/>} value={visitors.filter(v => v.status === "Pending").length} label="Pending Approval" color="amber"/><VStat icon={<CheckCircle2/>} value="24" label="Checked Out Today" color="blue"/></div>
    <div className="visitor-layout"><section className="visitor-register"><div className="visitor-toolbar"><label><Search size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search visitor, flat or entry ID..."/></label><div className="visitor-select"><select value={filter} onChange={e => setFilter(e.target.value)}><option>All Status</option><option>Pending</option><option>Approved</option><option>Checked In</option><option>Checked Out</option></select><ChevronDown size={15}/></div></div><div className="visitor-table-wrap"><table className="visitor-register-table"><thead><tr><th>Visitor</th><th>Purpose</th><th>Resident / Flat</th><th>Entry Time</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map(v => <tr key={v.id} className={selected.id === v.id ? "active" : ""} onClick={() => setSelected(v)}><td><b>{v.name}</b><small>{v.id}</small></td><td>{v.purpose}</td><td><b>{v.resident}</b><small>{v.flat}</small></td><td>{v.time}</td><td><em className={`visitor-status ${styleStatus(v.status)}`}>{v.status}</em></td><td><div><button title="View details" onClick={e => { e.stopPropagation(); setSelected(v); notify(`Viewing ${v.name}'s details.`); }}><Eye size={15}/></button>{v.status === "Pending" ? <button title="Approve visitor" onClick={e => { e.stopPropagation(); setSelected(v); setVisitors(list => list.map(item => item.id === v.id ? { ...item, status: "Approved" } : item)); notify(`${v.name} approved.`); }}><BadgeCheck size={15}/></button> : v.status === "Checked In" ? <button title="Check out visitor" onClick={e => { e.stopPropagation(); setSelected(v); setVisitors(list => list.map(item => item.id === v.id ? { ...item, status: "Checked Out" } : item)); notify(`${v.name} checked out.`); }}><LogOut size={15}/></button> : <button title="Check in visitor" onClick={e => { e.stopPropagation(); setSelected(v); setVisitors(list => list.map(item => item.id === v.id ? { ...item, status: "Checked In" } : item)); notify(`${v.name} checked in.`); }}><LogIn size={15}/></button>}</div></td></tr>)}</tbody></table></div><footer className="visitor-footer">Showing {visible.length} visitors <button onClick={() => notify("Visitor register exported.")}>Export Register</button></footer></section>
    <aside className="visitor-detail"><div className="visitor-detail-head"><div><span>Visitor Details</span><h2>{selected.name}</h2><small>{selected.id}</small></div><button onClick={() => notify("Visitor details refreshed.")}><X size={18}/></button></div><div className="visitor-avatar-large">{selected.name.split(" ").map(part => part[0]).join("")}</div><dl><div><dt>Purpose</dt><dd>{selected.purpose}</dd></div><div><dt>Visiting</dt><dd>{selected.resident} · {selected.flat}</dd></div><div><dt><Phone size={14}/> Mobile</dt><dd>{selected.phone}</dd></div><div><dt><Car size={14}/> Vehicle</dt><dd>{selected.vehicle}</dd></div><div><dt><CalendarDays size={14}/> Entry Time</dt><dd>{selected.time}</dd></div></dl><em className={`visitor-status ${styleStatus(selected.status)}`}>{selected.status}</em><div className="visitor-actions">{selected.status === "Pending" && <button className="visitor-primary" onClick={() => updateStatus("Approved")}><BadgeCheck size={16}/> Approve Entry</button>}{selected.status === "Approved" && <button className="visitor-primary" onClick={() => updateStatus("Checked In")}><LogIn size={16}/> Check In</button>}{selected.status === "Checked In" && <button className="visitor-primary" onClick={() => updateStatus("Checked Out")}><LogOut size={16}/> Check Out</button>}<button className="visitor-secondary" onClick={() => notify(`Call request sent to ${selected.resident}.`)}><Phone size={16}/> Contact Resident</button></div></aside></div>
    {showForm && <div className="visitor-modal-backdrop" onClick={() => setShowForm(false)}><form className="visitor-modal" onClick={e => e.stopPropagation()} onSubmit={addVisitor}><div><h2>Add Visitor</h2><button type="button" onClick={() => setShowForm(false)}><X size={19}/></button></div><label>Visitor name<input name="name" required placeholder="e.g. Suresh Nair"/></label><div className="visitor-form-grid"><label>Purpose<select name="purpose"><option>Personal Visit</option><option>Delivery</option><option>Service Provider</option></select></label><label>Flat number<input name="flat" required placeholder="e.g. A-1203"/></label></div><label>Mobile number<input name="phone" required placeholder="+91 98765 43210"/></label><footer><button type="button" onClick={() => setShowForm(false)}>Cancel</button><button className="visitor-primary">Approve Visitor</button></footer></form></div>}
  </div>;
}
function VStat({ icon, value, label, color }) { return <div className="visitor-stat"><span className={color}>{icon}</span><div><strong>{value}</strong><p>{label}</p></div></div>; }
export default Visitors;
